//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorConfig) DeepCopyInto(out *AcceleratorConfig) {
	*out = *in
	if in.AcceleratorCount != nil {
		in, out := &in.AcceleratorCount, &out.AcceleratorCount
		*out = new(int64)
		**out = **in
	}
	if in.AcceleratorType != nil {
		in, out := &in.AcceleratorType, &out.AcceleratorType
		*out = new(string)
		**out = **in
	}
	if in.GpuPartitionSize != nil {
		in, out := &in.GpuPartitionSize, &out.GpuPartitionSize
		*out = new(string)
		**out = **in
	}
	if in.MaxTimeSharedClientsPerGpu != nil {
		in, out := &in.MaxTimeSharedClientsPerGpu, &out.MaxTimeSharedClientsPerGpu
		*out = new(int64)
		**out = **in
	}
	if in.GpuSharingConfig != nil {
		in, out := &in.GpuSharingConfig, &out.GpuSharingConfig
		*out = new(GPUSharingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GpuDriverInstallationConfig != nil {
		in, out := &in.GpuDriverInstallationConfig, &out.GpuDriverInstallationConfig
		*out = new(GPUDriverInstallationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorConfig.
func (in *AcceleratorConfig) DeepCopy() *AcceleratorConfig {
	if in == nil {
		return nil
	}
	out := new(AcceleratorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalNodeNetworkConfig) DeepCopyInto(out *AdditionalNodeNetworkConfig) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Subnetwork != nil {
		in, out := &in.Subnetwork, &out.Subnetwork
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalNodeNetworkConfig.
func (in *AdditionalNodeNetworkConfig) DeepCopy() *AdditionalNodeNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(AdditionalNodeNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalPodNetworkConfig) DeepCopyInto(out *AdditionalPodNetworkConfig) {
	*out = *in
	if in.Subnetwork != nil {
		in, out := &in.Subnetwork, &out.Subnetwork
		*out = new(string)
		**out = **in
	}
	if in.SecondaryPodRange != nil {
		in, out := &in.SecondaryPodRange, &out.SecondaryPodRange
		*out = new(string)
		**out = **in
	}
	if in.MaxPodsPerNode != nil {
		in, out := &in.MaxPodsPerNode, &out.MaxPodsPerNode
		*out = new(MaxPodsConstraint)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalPodNetworkConfig.
func (in *AdditionalPodNetworkConfig) DeepCopy() *AdditionalPodNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(AdditionalPodNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedMachineFeatures) DeepCopyInto(out *AdvancedMachineFeatures) {
	*out = *in
	if in.ThreadsPerCore != nil {
		in, out := &in.ThreadsPerCore, &out.ThreadsPerCore
		*out = new(int64)
		**out = **in
	}
	if in.EnableNestedVirtualization != nil {
		in, out := &in.EnableNestedVirtualization, &out.EnableNestedVirtualization
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedMachineFeatures.
func (in *AdvancedMachineFeatures) DeepCopy() *AdvancedMachineFeatures {
	if in == nil {
		return nil
	}
	out := new(AdvancedMachineFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoUpgradeOptions) DeepCopyInto(out *AutoUpgradeOptions) {
	*out = *in
	if in.AutoUpgradeStartTime != nil {
		in, out := &in.AutoUpgradeStartTime, &out.AutoUpgradeStartTime
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoUpgradeOptions.
func (in *AutoUpgradeOptions) DeepCopy() *AutoUpgradeOptions {
	if in == nil {
		return nil
	}
	out := new(AutoUpgradeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BestEffortProvisioning) DeepCopyInto(out *BestEffortProvisioning) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MinProvisionNodes != nil {
		in, out := &in.MinProvisionNodes, &out.MinProvisionNodes
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BestEffortProvisioning.
func (in *BestEffortProvisioning) DeepCopy() *BestEffortProvisioning {
	if in == nil {
		return nil
	}
	out := new(BestEffortProvisioning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenSettings) DeepCopyInto(out *BlueGreenSettings) {
	*out = *in
	if in.StandardRolloutPolicy != nil {
		in, out := &in.StandardRolloutPolicy, &out.StandardRolloutPolicy
		*out = new(BlueGreenSettings_StandardRolloutPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoscaledRolloutPolicy != nil {
		in, out := &in.AutoscaledRolloutPolicy, &out.AutoscaledRolloutPolicy
		*out = new(BlueGreenSettings_AutoscaledRolloutPolicy)
		**out = **in
	}
	if in.NodePoolSoakDuration != nil {
		in, out := &in.NodePoolSoakDuration, &out.NodePoolSoakDuration
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenSettings.
func (in *BlueGreenSettings) DeepCopy() *BlueGreenSettings {
	if in == nil {
		return nil
	}
	out := new(BlueGreenSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenSettings_AutoscaledRolloutPolicy) DeepCopyInto(out *BlueGreenSettings_AutoscaledRolloutPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenSettings_AutoscaledRolloutPolicy.
func (in *BlueGreenSettings_AutoscaledRolloutPolicy) DeepCopy() *BlueGreenSettings_AutoscaledRolloutPolicy {
	if in == nil {
		return nil
	}
	out := new(BlueGreenSettings_AutoscaledRolloutPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueGreenSettings_StandardRolloutPolicy) DeepCopyInto(out *BlueGreenSettings_StandardRolloutPolicy) {
	*out = *in
	if in.BatchPercentage != nil {
		in, out := &in.BatchPercentage, &out.BatchPercentage
		*out = new(float32)
		**out = **in
	}
	if in.BatchNodeCount != nil {
		in, out := &in.BatchNodeCount, &out.BatchNodeCount
		*out = new(int32)
		**out = **in
	}
	if in.BatchSoakDuration != nil {
		in, out := &in.BatchSoakDuration, &out.BatchSoakDuration
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueGreenSettings_StandardRolloutPolicy.
func (in *BlueGreenSettings_StandardRolloutPolicy) DeepCopy() *BlueGreenSettings_StandardRolloutPolicy {
	if in == nil {
		return nil
	}
	out := new(BlueGreenSettings_StandardRolloutPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoolValue) DeepCopyInto(out *BoolValue) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoolValue.
func (in *BoolValue) DeepCopy() *BoolValue {
	if in == nil {
		return nil
	}
	out := new(BoolValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialNodes) DeepCopyInto(out *ConfidentialNodes) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialNodes.
func (in *ConfidentialNodes) DeepCopy() *ConfidentialNodes {
	if in == nil {
		return nil
	}
	out := new(ConfidentialNodes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerNodePool) DeepCopyInto(out *ContainerNodePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerNodePool.
func (in *ContainerNodePool) DeepCopy() *ContainerNodePool {
	if in == nil {
		return nil
	}
	out := new(ContainerNodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerNodePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerNodePoolList) DeepCopyInto(out *ContainerNodePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContainerNodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerNodePoolList.
func (in *ContainerNodePoolList) DeepCopy() *ContainerNodePoolList {
	if in == nil {
		return nil
	}
	out := new(ContainerNodePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContainerNodePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerNodePoolObservedState) DeepCopyInto(out *ContainerNodePoolObservedState) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerNodePoolObservedState.
func (in *ContainerNodePoolObservedState) DeepCopy() *ContainerNodePoolObservedState {
	if in == nil {
		return nil
	}
	out := new(ContainerNodePoolObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerNodePoolParent) DeepCopyInto(out *ContainerNodePoolParent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerNodePoolParent.
func (in *ContainerNodePoolParent) DeepCopy() *ContainerNodePoolParent {
	if in == nil {
		return nil
	}
	out := new(ContainerNodePoolParent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerNodePoolRef) DeepCopyInto(out *ContainerNodePoolRef) {
	*out = *in
	if in.parent != nil {
		in, out := &in.parent, &out.parent
		*out = new(ContainerNodePoolParent)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerNodePoolRef.
func (in *ContainerNodePoolRef) DeepCopy() *ContainerNodePoolRef {
	if in == nil {
		return nil
	}
	out := new(ContainerNodePoolRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerNodePoolSpec) DeepCopyInto(out *ContainerNodePoolSpec) {
	*out = *in
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(NodepoolAutoscaling)
		(*in).DeepCopyInto(*out)
	}
	out.ClusterRef = in.ClusterRef
	if in.InitialNodeCount != nil {
		in, out := &in.InitialNodeCount, &out.InitialNodeCount
		*out = new(int64)
		**out = **in
	}
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(NodepoolManagement)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxPodsPerNode != nil {
		in, out := &in.MaxPodsPerNode, &out.MaxPodsPerNode
		*out = new(int64)
		**out = **in
	}
	if in.NamePrefix != nil {
		in, out := &in.NamePrefix, &out.NamePrefix
		*out = new(string)
		**out = **in
	}
	if in.NetworkConfig != nil {
		in, out := &in.NetworkConfig, &out.NetworkConfig
		*out = new(NodepoolNetworkConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeConfig != nil {
		in, out := &in.NodeConfig, &out.NodeConfig
		*out = new(NodepoolNodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeCount != nil {
		in, out := &in.NodeCount, &out.NodeCount
		*out = new(int64)
		**out = **in
	}
	if in.NodeLocations != nil {
		in, out := &in.NodeLocations, &out.NodeLocations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PlacementPolicy != nil {
		in, out := &in.PlacementPolicy, &out.PlacementPolicy
		*out = new(NodepoolPlacementPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.UpgradeSettings != nil {
		in, out := &in.UpgradeSettings, &out.UpgradeSettings
		*out = new(NodepoolUpgradeSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerNodePoolSpec.
func (in *ContainerNodePoolSpec) DeepCopy() *ContainerNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerNodePoolStatus) DeepCopyInto(out *ContainerNodePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(ContainerNodePoolObservedState)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceGroupUrls != nil {
		in, out := &in.InstanceGroupUrls, &out.InstanceGroupUrls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedInstanceGroupUrls != nil {
		in, out := &in.ManagedInstanceGroupUrls, &out.ManagedInstanceGroupUrls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Operation != nil {
		in, out := &in.Operation, &out.Operation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerNodePoolStatus.
func (in *ContainerNodePoolStatus) DeepCopy() *ContainerNodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(ContainerNodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerdConfig) DeepCopyInto(out *ContainerdConfig) {
	*out = *in
	if in.PrivateRegistryAccessConfig != nil {
		in, out := &in.PrivateRegistryAccessConfig, &out.PrivateRegistryAccessConfig
		*out = new(ContainerdConfig_PrivateRegistryAccessConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerdConfig.
func (in *ContainerdConfig) DeepCopy() *ContainerdConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerdConfig_PrivateRegistryAccessConfig) DeepCopyInto(out *ContainerdConfig_PrivateRegistryAccessConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.CertificateAuthorityDomainConfig != nil {
		in, out := &in.CertificateAuthorityDomainConfig, &out.CertificateAuthorityDomainConfig
		*out = make([]ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerdConfig_PrivateRegistryAccessConfig.
func (in *ContainerdConfig_PrivateRegistryAccessConfig) DeepCopy() *ContainerdConfig_PrivateRegistryAccessConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerdConfig_PrivateRegistryAccessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig) DeepCopyInto(out *ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig) {
	*out = *in
	if in.Fqdns != nil {
		in, out := &in.Fqdns, &out.Fqdns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GcpSecretManagerCertificateConfig != nil {
		in, out := &in.GcpSecretManagerCertificateConfig, &out.GcpSecretManagerCertificateConfig
		*out = new(ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig_GCPSecretManagerCertificateConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig.
func (in *ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig) DeepCopy() *ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig_GCPSecretManagerCertificateConfig) DeepCopyInto(out *ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig_GCPSecretManagerCertificateConfig) {
	*out = *in
	if in.SecretUri != nil {
		in, out := &in.SecretUri, &out.SecretUri
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig_GCPSecretManagerCertificateConfig.
func (in *ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig_GCPSecretManagerCertificateConfig) DeepCopy() *ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig_GCPSecretManagerCertificateConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerdConfig_PrivateRegistryAccessConfig_CertificateAuthorityDomainConfig_GCPSecretManagerCertificateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralStorageConfig) DeepCopyInto(out *EphemeralStorageConfig) {
	*out = *in
	if in.LocalSsdCount != nil {
		in, out := &in.LocalSsdCount, &out.LocalSsdCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralStorageConfig.
func (in *EphemeralStorageConfig) DeepCopy() *EphemeralStorageConfig {
	if in == nil {
		return nil
	}
	out := new(EphemeralStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemeralStorageLocalSsdConfig) DeepCopyInto(out *EphemeralStorageLocalSsdConfig) {
	*out = *in
	if in.LocalSsdCount != nil {
		in, out := &in.LocalSsdCount, &out.LocalSsdCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemeralStorageLocalSsdConfig.
func (in *EphemeralStorageLocalSsdConfig) DeepCopy() *EphemeralStorageLocalSsdConfig {
	if in == nil {
		return nil
	}
	out := new(EphemeralStorageLocalSsdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FastSocket) DeepCopyInto(out *FastSocket) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FastSocket.
func (in *FastSocket) DeepCopy() *FastSocket {
	if in == nil {
		return nil
	}
	out := new(FastSocket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDriverInstallationConfig) DeepCopyInto(out *GPUDriverInstallationConfig) {
	*out = *in
	if in.GpuDriverVersion != nil {
		in, out := &in.GpuDriverVersion, &out.GpuDriverVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDriverInstallationConfig.
func (in *GPUDriverInstallationConfig) DeepCopy() *GPUDriverInstallationConfig {
	if in == nil {
		return nil
	}
	out := new(GPUDriverInstallationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSharingConfig) DeepCopyInto(out *GPUSharingConfig) {
	*out = *in
	if in.MaxSharedClientsPerGpu != nil {
		in, out := &in.MaxSharedClientsPerGpu, &out.MaxSharedClientsPerGpu
		*out = new(int64)
		**out = **in
	}
	if in.GpuSharingStrategy != nil {
		in, out := &in.GpuSharingStrategy, &out.GpuSharingStrategy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSharingConfig.
func (in *GPUSharingConfig) DeepCopy() *GPUSharingConfig {
	if in == nil {
		return nil
	}
	out := new(GPUSharingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcfsConfig) DeepCopyInto(out *GcfsConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcfsConfig.
func (in *GcfsConfig) DeepCopy() *GcfsConfig {
	if in == nil {
		return nil
	}
	out := new(GcfsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostMaintenancePolicy) DeepCopyInto(out *HostMaintenancePolicy) {
	*out = *in
	if in.MaintenanceInterval != nil {
		in, out := &in.MaintenanceInterval, &out.MaintenanceInterval
		*out = new(string)
		**out = **in
	}
	if in.OpportunisticMaintenanceStrategy != nil {
		in, out := &in.OpportunisticMaintenanceStrategy, &out.OpportunisticMaintenanceStrategy
		*out = new(HostMaintenancePolicy_OpportunisticMaintenanceStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostMaintenancePolicy.
func (in *HostMaintenancePolicy) DeepCopy() *HostMaintenancePolicy {
	if in == nil {
		return nil
	}
	out := new(HostMaintenancePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostMaintenancePolicy_OpportunisticMaintenanceStrategy) DeepCopyInto(out *HostMaintenancePolicy_OpportunisticMaintenanceStrategy) {
	*out = *in
	if in.NodeIdleTimeWindow != nil {
		in, out := &in.NodeIdleTimeWindow, &out.NodeIdleTimeWindow
		*out = new(string)
		**out = **in
	}
	if in.MaintenanceAvailabilityWindow != nil {
		in, out := &in.MaintenanceAvailabilityWindow, &out.MaintenanceAvailabilityWindow
		*out = new(string)
		**out = **in
	}
	if in.MinNodesPerPool != nil {
		in, out := &in.MinNodesPerPool, &out.MinNodesPerPool
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostMaintenancePolicy_OpportunisticMaintenanceStrategy.
func (in *HostMaintenancePolicy_OpportunisticMaintenanceStrategy) DeepCopy() *HostMaintenancePolicy_OpportunisticMaintenanceStrategy {
	if in == nil {
		return nil
	}
	out := new(HostMaintenancePolicy_OpportunisticMaintenanceStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinuxNodeConfig) DeepCopyInto(out *LinuxNodeConfig) {
	*out = *in
	if in.Sysctls != nil {
		in, out := &in.Sysctls, &out.Sysctls
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CgroupMode != nil {
		in, out := &in.CgroupMode, &out.CgroupMode
		*out = new(string)
		**out = **in
	}
	if in.Hugepages != nil {
		in, out := &in.Hugepages, &out.Hugepages
		*out = new(LinuxNodeConfig_HugepagesConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinuxNodeConfig.
func (in *LinuxNodeConfig) DeepCopy() *LinuxNodeConfig {
	if in == nil {
		return nil
	}
	out := new(LinuxNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinuxNodeConfig_HugepagesConfig) DeepCopyInto(out *LinuxNodeConfig_HugepagesConfig) {
	*out = *in
	if in.HugepageSize2m != nil {
		in, out := &in.HugepageSize2m, &out.HugepageSize2m
		*out = new(int32)
		**out = **in
	}
	if in.HugepageSize1g != nil {
		in, out := &in.HugepageSize1g, &out.HugepageSize1g
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinuxNodeConfig_HugepagesConfig.
func (in *LinuxNodeConfig_HugepagesConfig) DeepCopy() *LinuxNodeConfig_HugepagesConfig {
	if in == nil {
		return nil
	}
	out := new(LinuxNodeConfig_HugepagesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalNvmeSsdBlockConfig) DeepCopyInto(out *LocalNvmeSsdBlockConfig) {
	*out = *in
	if in.LocalSsdCount != nil {
		in, out := &in.LocalSsdCount, &out.LocalSsdCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalNvmeSsdBlockConfig.
func (in *LocalNvmeSsdBlockConfig) DeepCopy() *LocalNvmeSsdBlockConfig {
	if in == nil {
		return nil
	}
	out := new(LocalNvmeSsdBlockConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingVariantConfig) DeepCopyInto(out *LoggingVariantConfig) {
	*out = *in
	if in.Variant != nil {
		in, out := &in.Variant, &out.Variant
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingVariantConfig.
func (in *LoggingVariantConfig) DeepCopy() *LoggingVariantConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingVariantConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaxPodsConstraint) DeepCopyInto(out *MaxPodsConstraint) {
	*out = *in
	if in.MaxPodsPerNode != nil {
		in, out := &in.MaxPodsPerNode, &out.MaxPodsPerNode
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaxPodsConstraint.
func (in *MaxPodsConstraint) DeepCopy() *MaxPodsConstraint {
	if in == nil {
		return nil
	}
	out := new(MaxPodsConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfig) DeepCopyInto(out *NodeConfig) {
	*out = *in
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.DiskSizeGb != nil {
		in, out := &in.DiskSizeGb, &out.DiskSizeGb
		*out = new(int32)
		**out = **in
	}
	if in.OauthScopes != nil {
		in, out := &in.OauthScopes, &out.OauthScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImageType != nil {
		in, out := &in.ImageType, &out.ImageType
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LocalSsdCount != nil {
		in, out := &in.LocalSsdCount, &out.LocalSsdCount
		*out = new(int32)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Preemptible != nil {
		in, out := &in.Preemptible, &out.Preemptible
		*out = new(bool)
		**out = **in
	}
	if in.Accelerators != nil {
		in, out := &in.Accelerators, &out.Accelerators
		*out = make([]AcceleratorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SandboxConfig != nil {
		in, out := &in.SandboxConfig, &out.SandboxConfig
		*out = new(SandboxConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeGroup != nil {
		in, out := &in.NodeGroup, &out.NodeGroup
		*out = new(string)
		**out = **in
	}
	if in.ReservationAffinity != nil {
		in, out := &in.ReservationAffinity, &out.ReservationAffinity
		*out = new(ReservationAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.DiskType != nil {
		in, out := &in.DiskType, &out.DiskType
		*out = new(string)
		**out = **in
	}
	if in.MinCpuPlatform != nil {
		in, out := &in.MinCpuPlatform, &out.MinCpuPlatform
		*out = new(string)
		**out = **in
	}
	if in.WorkloadMetadataConfig != nil {
		in, out := &in.WorkloadMetadataConfig, &out.WorkloadMetadataConfig
		*out = new(WorkloadMetadataConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]NodeTaint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BootDiskKmsKey != nil {
		in, out := &in.BootDiskKmsKey, &out.BootDiskKmsKey
		*out = new(string)
		**out = **in
	}
	if in.ShieldedInstanceConfig != nil {
		in, out := &in.ShieldedInstanceConfig, &out.ShieldedInstanceConfig
		*out = new(ShieldedInstanceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LinuxNodeConfig != nil {
		in, out := &in.LinuxNodeConfig, &out.LinuxNodeConfig
		*out = new(LinuxNodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KubeletConfig != nil {
		in, out := &in.KubeletConfig, &out.KubeletConfig
		*out = new(NodeKubeletConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EphemeralStorageConfig != nil {
		in, out := &in.EphemeralStorageConfig, &out.EphemeralStorageConfig
		*out = new(EphemeralStorageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GcfsConfig != nil {
		in, out := &in.GcfsConfig, &out.GcfsConfig
		*out = new(GcfsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AdvancedMachineFeatures != nil {
		in, out := &in.AdvancedMachineFeatures, &out.AdvancedMachineFeatures
		*out = new(AdvancedMachineFeatures)
		(*in).DeepCopyInto(*out)
	}
	if in.Gvnic != nil {
		in, out := &in.Gvnic, &out.Gvnic
		*out = new(VirtualNIC)
		(*in).DeepCopyInto(*out)
	}
	if in.Spot != nil {
		in, out := &in.Spot, &out.Spot
		*out = new(bool)
		**out = **in
	}
	if in.ConfidentialNodes != nil {
		in, out := &in.ConfidentialNodes, &out.ConfidentialNodes
		*out = new(ConfidentialNodes)
		(*in).DeepCopyInto(*out)
	}
	if in.FastSocket != nil {
		in, out := &in.FastSocket, &out.FastSocket
		*out = new(FastSocket)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceLabels != nil {
		in, out := &in.ResourceLabels, &out.ResourceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LoggingConfig != nil {
		in, out := &in.LoggingConfig, &out.LoggingConfig
		*out = new(NodePoolLoggingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.WindowsNodeConfig != nil {
		in, out := &in.WindowsNodeConfig, &out.WindowsNodeConfig
		*out = new(WindowsNodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalNvmeSsdBlockConfig != nil {
		in, out := &in.LocalNvmeSsdBlockConfig, &out.LocalNvmeSsdBlockConfig
		*out = new(LocalNvmeSsdBlockConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EphemeralStorageLocalSsdConfig != nil {
		in, out := &in.EphemeralStorageLocalSsdConfig, &out.EphemeralStorageLocalSsdConfig
		*out = new(EphemeralStorageLocalSsdConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SoleTenantConfig != nil {
		in, out := &in.SoleTenantConfig, &out.SoleTenantConfig
		*out = new(SoleTenantConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerdConfig != nil {
		in, out := &in.ContainerdConfig, &out.ContainerdConfig
		*out = new(ContainerdConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HostMaintenancePolicy != nil {
		in, out := &in.HostMaintenancePolicy, &out.HostMaintenancePolicy
		*out = new(HostMaintenancePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceManagerTags != nil {
		in, out := &in.ResourceManagerTags, &out.ResourceManagerTags
		*out = new(ResourceManagerTags)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableConfidentialStorage != nil {
		in, out := &in.EnableConfidentialStorage, &out.EnableConfidentialStorage
		*out = new(bool)
		**out = **in
	}
	if in.SecondaryBootDisks != nil {
		in, out := &in.SecondaryBootDisks, &out.SecondaryBootDisks
		*out = make([]SecondaryBootDisk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecondaryBootDiskUpdateStrategy != nil {
		in, out := &in.SecondaryBootDiskUpdateStrategy, &out.SecondaryBootDiskUpdateStrategy
		*out = new(SecondaryBootDiskUpdateStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfig.
func (in *NodeConfig) DeepCopy() *NodeConfig {
	if in == nil {
		return nil
	}
	out := new(NodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeKubeletConfig) DeepCopyInto(out *NodeKubeletConfig) {
	*out = *in
	if in.CpuManagerPolicy != nil {
		in, out := &in.CpuManagerPolicy, &out.CpuManagerPolicy
		*out = new(string)
		**out = **in
	}
	if in.CpuCfsQuota != nil {
		in, out := &in.CpuCfsQuota, &out.CpuCfsQuota
		*out = new(BoolValue)
		(*in).DeepCopyInto(*out)
	}
	if in.CpuCfsQuotaPeriod != nil {
		in, out := &in.CpuCfsQuotaPeriod, &out.CpuCfsQuotaPeriod
		*out = new(string)
		**out = **in
	}
	if in.PodPidsLimit != nil {
		in, out := &in.PodPidsLimit, &out.PodPidsLimit
		*out = new(int64)
		**out = **in
	}
	if in.InsecureKubeletReadonlyPortEnabled != nil {
		in, out := &in.InsecureKubeletReadonlyPortEnabled, &out.InsecureKubeletReadonlyPortEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeKubeletConfig.
func (in *NodeKubeletConfig) DeepCopy() *NodeKubeletConfig {
	if in == nil {
		return nil
	}
	out := new(NodeKubeletConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeManagement) DeepCopyInto(out *NodeManagement) {
	*out = *in
	if in.AutoUpgrade != nil {
		in, out := &in.AutoUpgrade, &out.AutoUpgrade
		*out = new(bool)
		**out = **in
	}
	if in.AutoRepair != nil {
		in, out := &in.AutoRepair, &out.AutoRepair
		*out = new(bool)
		**out = **in
	}
	if in.UpgradeOptions != nil {
		in, out := &in.UpgradeOptions, &out.UpgradeOptions
		*out = new(AutoUpgradeOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeManagement.
func (in *NodeManagement) DeepCopy() *NodeManagement {
	if in == nil {
		return nil
	}
	out := new(NodeManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkConfig) DeepCopyInto(out *NodeNetworkConfig) {
	*out = *in
	if in.CreatePodRange != nil {
		in, out := &in.CreatePodRange, &out.CreatePodRange
		*out = new(bool)
		**out = **in
	}
	if in.PodRange != nil {
		in, out := &in.PodRange, &out.PodRange
		*out = new(string)
		**out = **in
	}
	if in.PodIpv4CidrBlock != nil {
		in, out := &in.PodIpv4CidrBlock, &out.PodIpv4CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.EnablePrivateNodes != nil {
		in, out := &in.EnablePrivateNodes, &out.EnablePrivateNodes
		*out = new(bool)
		**out = **in
	}
	if in.NetworkPerformanceConfig != nil {
		in, out := &in.NetworkPerformanceConfig, &out.NetworkPerformanceConfig
		*out = new(NodeNetworkConfig_NetworkPerformanceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PodCidrOverprovisionConfig != nil {
		in, out := &in.PodCidrOverprovisionConfig, &out.PodCidrOverprovisionConfig
		*out = new(PodCIDROverprovisionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalNodeNetworkConfigs != nil {
		in, out := &in.AdditionalNodeNetworkConfigs, &out.AdditionalNodeNetworkConfigs
		*out = make([]AdditionalNodeNetworkConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdditionalPodNetworkConfigs != nil {
		in, out := &in.AdditionalPodNetworkConfigs, &out.AdditionalPodNetworkConfigs
		*out = make([]AdditionalPodNetworkConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodIpv4RangeUtilization != nil {
		in, out := &in.PodIpv4RangeUtilization, &out.PodIpv4RangeUtilization
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkConfig.
func (in *NodeNetworkConfig) DeepCopy() *NodeNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkConfig_NetworkPerformanceConfig) DeepCopyInto(out *NodeNetworkConfig_NetworkPerformanceConfig) {
	*out = *in
	if in.TotalEgressBandwidthTier != nil {
		in, out := &in.TotalEgressBandwidthTier, &out.TotalEgressBandwidthTier
		*out = new(string)
		**out = **in
	}
	if in.ExternalIpEgressBandwidthTier != nil {
		in, out := &in.ExternalIpEgressBandwidthTier, &out.ExternalIpEgressBandwidthTier
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkConfig_NetworkPerformanceConfig.
func (in *NodeNetworkConfig_NetworkPerformanceConfig) DeepCopy() *NodeNetworkConfig_NetworkPerformanceConfig {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkConfig_NetworkPerformanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool) DeepCopyInto(out *NodePool) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(NodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InitialNodeCount != nil {
		in, out := &in.InitialNodeCount, &out.InitialNodeCount
		*out = new(int32)
		**out = **in
	}
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NetworkConfig != nil {
		in, out := &in.NetworkConfig, &out.NetworkConfig
		*out = new(NodeNetworkConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SelfLink != nil {
		in, out := &in.SelfLink, &out.SelfLink
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.InstanceGroupUrls != nil {
		in, out := &in.InstanceGroupUrls, &out.InstanceGroupUrls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StatusMessage != nil {
		in, out := &in.StatusMessage, &out.StatusMessage
		*out = new(string)
		**out = **in
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(NodePoolAutoscaling)
		(*in).DeepCopyInto(*out)
	}
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(NodeManagement)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxPodsConstraint != nil {
		in, out := &in.MaxPodsConstraint, &out.MaxPodsConstraint
		*out = new(MaxPodsConstraint)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]StatusCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodIpv4CidrSize != nil {
		in, out := &in.PodIpv4CidrSize, &out.PodIpv4CidrSize
		*out = new(int32)
		**out = **in
	}
	if in.UpgradeSettings != nil {
		in, out := &in.UpgradeSettings, &out.UpgradeSettings
		*out = new(NodePool_UpgradeSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.PlacementPolicy != nil {
		in, out := &in.PlacementPolicy, &out.PlacementPolicy
		*out = new(NodePool_PlacementPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdateInfo != nil {
		in, out := &in.UpdateInfo, &out.UpdateInfo
		*out = new(NodePool_UpdateInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Etag != nil {
		in, out := &in.Etag, &out.Etag
		*out = new(string)
		**out = **in
	}
	if in.QueuedProvisioning != nil {
		in, out := &in.QueuedProvisioning, &out.QueuedProvisioning
		*out = new(NodePool_QueuedProvisioning)
		(*in).DeepCopyInto(*out)
	}
	if in.BestEffortProvisioning != nil {
		in, out := &in.BestEffortProvisioning, &out.BestEffortProvisioning
		*out = new(BestEffortProvisioning)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool.
func (in *NodePool) DeepCopy() *NodePool {
	if in == nil {
		return nil
	}
	out := new(NodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolAutoscaling) DeepCopyInto(out *NodePoolAutoscaling) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MinNodeCount != nil {
		in, out := &in.MinNodeCount, &out.MinNodeCount
		*out = new(int32)
		**out = **in
	}
	if in.MaxNodeCount != nil {
		in, out := &in.MaxNodeCount, &out.MaxNodeCount
		*out = new(int32)
		**out = **in
	}
	if in.Autoprovisioned != nil {
		in, out := &in.Autoprovisioned, &out.Autoprovisioned
		*out = new(bool)
		**out = **in
	}
	if in.LocationPolicy != nil {
		in, out := &in.LocationPolicy, &out.LocationPolicy
		*out = new(string)
		**out = **in
	}
	if in.TotalMinNodeCount != nil {
		in, out := &in.TotalMinNodeCount, &out.TotalMinNodeCount
		*out = new(int32)
		**out = **in
	}
	if in.TotalMaxNodeCount != nil {
		in, out := &in.TotalMaxNodeCount, &out.TotalMaxNodeCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolAutoscaling.
func (in *NodePoolAutoscaling) DeepCopy() *NodePoolAutoscaling {
	if in == nil {
		return nil
	}
	out := new(NodePoolAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolLoggingConfig) DeepCopyInto(out *NodePoolLoggingConfig) {
	*out = *in
	if in.VariantConfig != nil {
		in, out := &in.VariantConfig, &out.VariantConfig
		*out = new(LoggingVariantConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolLoggingConfig.
func (in *NodePoolLoggingConfig) DeepCopy() *NodePoolLoggingConfig {
	if in == nil {
		return nil
	}
	out := new(NodePoolLoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool_PlacementPolicy) DeepCopyInto(out *NodePool_PlacementPolicy) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.TpuTopology != nil {
		in, out := &in.TpuTopology, &out.TpuTopology
		*out = new(string)
		**out = **in
	}
	if in.PolicyName != nil {
		in, out := &in.PolicyName, &out.PolicyName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool_PlacementPolicy.
func (in *NodePool_PlacementPolicy) DeepCopy() *NodePool_PlacementPolicy {
	if in == nil {
		return nil
	}
	out := new(NodePool_PlacementPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool_QueuedProvisioning) DeepCopyInto(out *NodePool_QueuedProvisioning) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool_QueuedProvisioning.
func (in *NodePool_QueuedProvisioning) DeepCopy() *NodePool_QueuedProvisioning {
	if in == nil {
		return nil
	}
	out := new(NodePool_QueuedProvisioning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool_UpdateInfo) DeepCopyInto(out *NodePool_UpdateInfo) {
	*out = *in
	if in.BlueGreenInfo != nil {
		in, out := &in.BlueGreenInfo, &out.BlueGreenInfo
		*out = new(NodePool_UpdateInfo_BlueGreenInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool_UpdateInfo.
func (in *NodePool_UpdateInfo) DeepCopy() *NodePool_UpdateInfo {
	if in == nil {
		return nil
	}
	out := new(NodePool_UpdateInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool_UpdateInfo_BlueGreenInfo) DeepCopyInto(out *NodePool_UpdateInfo_BlueGreenInfo) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(string)
		**out = **in
	}
	if in.BlueInstanceGroupUrls != nil {
		in, out := &in.BlueInstanceGroupUrls, &out.BlueInstanceGroupUrls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GreenInstanceGroupUrls != nil {
		in, out := &in.GreenInstanceGroupUrls, &out.GreenInstanceGroupUrls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BluePoolDeletionStartTime != nil {
		in, out := &in.BluePoolDeletionStartTime, &out.BluePoolDeletionStartTime
		*out = new(string)
		**out = **in
	}
	if in.GreenPoolVersion != nil {
		in, out := &in.GreenPoolVersion, &out.GreenPoolVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool_UpdateInfo_BlueGreenInfo.
func (in *NodePool_UpdateInfo_BlueGreenInfo) DeepCopy() *NodePool_UpdateInfo_BlueGreenInfo {
	if in == nil {
		return nil
	}
	out := new(NodePool_UpdateInfo_BlueGreenInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool_UpgradeSettings) DeepCopyInto(out *NodePool_UpgradeSettings) {
	*out = *in
	if in.MaxSurge != nil {
		in, out := &in.MaxSurge, &out.MaxSurge
		*out = new(int32)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(int32)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(string)
		**out = **in
	}
	if in.BlueGreenSettings != nil {
		in, out := &in.BlueGreenSettings, &out.BlueGreenSettings
		*out = new(BlueGreenSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool_UpgradeSettings.
func (in *NodePool_UpgradeSettings) DeepCopy() *NodePool_UpgradeSettings {
	if in == nil {
		return nil
	}
	out := new(NodePool_UpgradeSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTaint) DeepCopyInto(out *NodeTaint) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Effect != nil {
		in, out := &in.Effect, &out.Effect
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTaint.
func (in *NodeTaint) DeepCopy() *NodeTaint {
	if in == nil {
		return nil
	}
	out := new(NodeTaint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolAdditionalNodeNetworkConfigs) DeepCopyInto(out *NodepoolAdditionalNodeNetworkConfigs) {
	*out = *in
	if in.NetworkRef != nil {
		in, out := &in.NetworkRef, &out.NetworkRef
		*out = new(v1alpha1.ResourceRef)
		**out = **in
	}
	if in.SubnetworkRef != nil {
		in, out := &in.SubnetworkRef, &out.SubnetworkRef
		*out = new(v1alpha1.ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolAdditionalNodeNetworkConfigs.
func (in *NodepoolAdditionalNodeNetworkConfigs) DeepCopy() *NodepoolAdditionalNodeNetworkConfigs {
	if in == nil {
		return nil
	}
	out := new(NodepoolAdditionalNodeNetworkConfigs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolAdditionalPodNetworkConfigs) DeepCopyInto(out *NodepoolAdditionalPodNetworkConfigs) {
	*out = *in
	if in.MaxPodsPerNode != nil {
		in, out := &in.MaxPodsPerNode, &out.MaxPodsPerNode
		*out = new(int64)
		**out = **in
	}
	if in.SecondaryPodRange != nil {
		in, out := &in.SecondaryPodRange, &out.SecondaryPodRange
		*out = new(string)
		**out = **in
	}
	if in.SubnetworkRef != nil {
		in, out := &in.SubnetworkRef, &out.SubnetworkRef
		*out = new(v1alpha1.ResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolAdditionalPodNetworkConfigs.
func (in *NodepoolAdditionalPodNetworkConfigs) DeepCopy() *NodepoolAdditionalPodNetworkConfigs {
	if in == nil {
		return nil
	}
	out := new(NodepoolAdditionalPodNetworkConfigs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolAdvancedMachineFeatures) DeepCopyInto(out *NodepoolAdvancedMachineFeatures) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolAdvancedMachineFeatures.
func (in *NodepoolAdvancedMachineFeatures) DeepCopy() *NodepoolAdvancedMachineFeatures {
	if in == nil {
		return nil
	}
	out := new(NodepoolAdvancedMachineFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolAutoscaling) DeepCopyInto(out *NodepoolAutoscaling) {
	*out = *in
	if in.LocationPolicy != nil {
		in, out := &in.LocationPolicy, &out.LocationPolicy
		*out = new(string)
		**out = **in
	}
	if in.MaxNodeCount != nil {
		in, out := &in.MaxNodeCount, &out.MaxNodeCount
		*out = new(int64)
		**out = **in
	}
	if in.MinNodeCount != nil {
		in, out := &in.MinNodeCount, &out.MinNodeCount
		*out = new(int64)
		**out = **in
	}
	if in.TotalMaxNodeCount != nil {
		in, out := &in.TotalMaxNodeCount, &out.TotalMaxNodeCount
		*out = new(int64)
		**out = **in
	}
	if in.TotalMinNodeCount != nil {
		in, out := &in.TotalMinNodeCount, &out.TotalMinNodeCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolAutoscaling.
func (in *NodepoolAutoscaling) DeepCopy() *NodepoolAutoscaling {
	if in == nil {
		return nil
	}
	out := new(NodepoolAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolBlueGreenSettings) DeepCopyInto(out *NodepoolBlueGreenSettings) {
	*out = *in
	if in.NodePoolSoakDuration != nil {
		in, out := &in.NodePoolSoakDuration, &out.NodePoolSoakDuration
		*out = new(string)
		**out = **in
	}
	in.StandardRolloutPolicy.DeepCopyInto(&out.StandardRolloutPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolBlueGreenSettings.
func (in *NodepoolBlueGreenSettings) DeepCopy() *NodepoolBlueGreenSettings {
	if in == nil {
		return nil
	}
	out := new(NodepoolBlueGreenSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolConfidentialNodes) DeepCopyInto(out *NodepoolConfidentialNodes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolConfidentialNodes.
func (in *NodepoolConfidentialNodes) DeepCopy() *NodepoolConfidentialNodes {
	if in == nil {
		return nil
	}
	out := new(NodepoolConfidentialNodes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolEphemeralStorageConfig) DeepCopyInto(out *NodepoolEphemeralStorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolEphemeralStorageConfig.
func (in *NodepoolEphemeralStorageConfig) DeepCopy() *NodepoolEphemeralStorageConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolEphemeralStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolEphemeralStorageLocalSsdConfig) DeepCopyInto(out *NodepoolEphemeralStorageLocalSsdConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolEphemeralStorageLocalSsdConfig.
func (in *NodepoolEphemeralStorageLocalSsdConfig) DeepCopy() *NodepoolEphemeralStorageLocalSsdConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolEphemeralStorageLocalSsdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolFastSocket) DeepCopyInto(out *NodepoolFastSocket) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolFastSocket.
func (in *NodepoolFastSocket) DeepCopy() *NodepoolFastSocket {
	if in == nil {
		return nil
	}
	out := new(NodepoolFastSocket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolGcfsConfig) DeepCopyInto(out *NodepoolGcfsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolGcfsConfig.
func (in *NodepoolGcfsConfig) DeepCopy() *NodepoolGcfsConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolGcfsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolGpuDriverInstallationConfig) DeepCopyInto(out *NodepoolGpuDriverInstallationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolGpuDriverInstallationConfig.
func (in *NodepoolGpuDriverInstallationConfig) DeepCopy() *NodepoolGpuDriverInstallationConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolGpuDriverInstallationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolGpuSharingConfig) DeepCopyInto(out *NodepoolGpuSharingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolGpuSharingConfig.
func (in *NodepoolGpuSharingConfig) DeepCopy() *NodepoolGpuSharingConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolGpuSharingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolGuestAccelerator) DeepCopyInto(out *NodepoolGuestAccelerator) {
	*out = *in
	if in.GpuDriverInstallationConfig != nil {
		in, out := &in.GpuDriverInstallationConfig, &out.GpuDriverInstallationConfig
		*out = new(NodepoolGpuDriverInstallationConfig)
		**out = **in
	}
	if in.GpuPartitionSize != nil {
		in, out := &in.GpuPartitionSize, &out.GpuPartitionSize
		*out = new(string)
		**out = **in
	}
	if in.GpuSharingConfig != nil {
		in, out := &in.GpuSharingConfig, &out.GpuSharingConfig
		*out = new(NodepoolGpuSharingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolGuestAccelerator.
func (in *NodepoolGuestAccelerator) DeepCopy() *NodepoolGuestAccelerator {
	if in == nil {
		return nil
	}
	out := new(NodepoolGuestAccelerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolGvnic) DeepCopyInto(out *NodepoolGvnic) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolGvnic.
func (in *NodepoolGvnic) DeepCopy() *NodepoolGvnic {
	if in == nil {
		return nil
	}
	out := new(NodepoolGvnic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolHostMaintenancePolicy) DeepCopyInto(out *NodepoolHostMaintenancePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolHostMaintenancePolicy.
func (in *NodepoolHostMaintenancePolicy) DeepCopy() *NodepoolHostMaintenancePolicy {
	if in == nil {
		return nil
	}
	out := new(NodepoolHostMaintenancePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolKubeletConfig) DeepCopyInto(out *NodepoolKubeletConfig) {
	*out = *in
	if in.CpuCfsQuota != nil {
		in, out := &in.CpuCfsQuota, &out.CpuCfsQuota
		*out = new(bool)
		**out = **in
	}
	if in.CpuCfsQuotaPeriod != nil {
		in, out := &in.CpuCfsQuotaPeriod, &out.CpuCfsQuotaPeriod
		*out = new(string)
		**out = **in
	}
	if in.PodPidsLimit != nil {
		in, out := &in.PodPidsLimit, &out.PodPidsLimit
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolKubeletConfig.
func (in *NodepoolKubeletConfig) DeepCopy() *NodepoolKubeletConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolKubeletConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolLinuxNodeConfig) DeepCopyInto(out *NodepoolLinuxNodeConfig) {
	*out = *in
	if in.CgroupMode != nil {
		in, out := &in.CgroupMode, &out.CgroupMode
		*out = new(string)
		**out = **in
	}
	if in.Sysctls != nil {
		in, out := &in.Sysctls, &out.Sysctls
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolLinuxNodeConfig.
func (in *NodepoolLinuxNodeConfig) DeepCopy() *NodepoolLinuxNodeConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolLinuxNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolLocalNvmeSsdBlockConfig) DeepCopyInto(out *NodepoolLocalNvmeSsdBlockConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolLocalNvmeSsdBlockConfig.
func (in *NodepoolLocalNvmeSsdBlockConfig) DeepCopy() *NodepoolLocalNvmeSsdBlockConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolLocalNvmeSsdBlockConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolManagement) DeepCopyInto(out *NodepoolManagement) {
	*out = *in
	if in.AutoRepair != nil {
		in, out := &in.AutoRepair, &out.AutoRepair
		*out = new(bool)
		**out = **in
	}
	if in.AutoUpgrade != nil {
		in, out := &in.AutoUpgrade, &out.AutoUpgrade
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolManagement.
func (in *NodepoolManagement) DeepCopy() *NodepoolManagement {
	if in == nil {
		return nil
	}
	out := new(NodepoolManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolNetworkConfig) DeepCopyInto(out *NodepoolNetworkConfig) {
	*out = *in
	if in.AdditionalNodeNetworkConfigs != nil {
		in, out := &in.AdditionalNodeNetworkConfigs, &out.AdditionalNodeNetworkConfigs
		*out = make([]NodepoolAdditionalNodeNetworkConfigs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdditionalPodNetworkConfigs != nil {
		in, out := &in.AdditionalPodNetworkConfigs, &out.AdditionalPodNetworkConfigs
		*out = make([]NodepoolAdditionalPodNetworkConfigs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreatePodRange != nil {
		in, out := &in.CreatePodRange, &out.CreatePodRange
		*out = new(bool)
		**out = **in
	}
	if in.EnablePrivateNodes != nil {
		in, out := &in.EnablePrivateNodes, &out.EnablePrivateNodes
		*out = new(bool)
		**out = **in
	}
	if in.PodCidrOverprovisionConfig != nil {
		in, out := &in.PodCidrOverprovisionConfig, &out.PodCidrOverprovisionConfig
		*out = new(NodepoolPodCidrOverprovisionConfig)
		**out = **in
	}
	if in.PodIpv4CidrBlock != nil {
		in, out := &in.PodIpv4CidrBlock, &out.PodIpv4CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.PodRange != nil {
		in, out := &in.PodRange, &out.PodRange
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolNetworkConfig.
func (in *NodepoolNetworkConfig) DeepCopy() *NodepoolNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolNodeAffinity) DeepCopyInto(out *NodepoolNodeAffinity) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolNodeAffinity.
func (in *NodepoolNodeAffinity) DeepCopy() *NodepoolNodeAffinity {
	if in == nil {
		return nil
	}
	out := new(NodepoolNodeAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolNodeConfig) DeepCopyInto(out *NodepoolNodeConfig) {
	*out = *in
	if in.AdvancedMachineFeatures != nil {
		in, out := &in.AdvancedMachineFeatures, &out.AdvancedMachineFeatures
		*out = new(NodepoolAdvancedMachineFeatures)
		**out = **in
	}
	if in.BootDiskKMSCryptoKeyRef != nil {
		in, out := &in.BootDiskKMSCryptoKeyRef, &out.BootDiskKMSCryptoKeyRef
		*out = new(v1alpha1.ResourceRef)
		**out = **in
	}
	if in.ConfidentialNodes != nil {
		in, out := &in.ConfidentialNodes, &out.ConfidentialNodes
		*out = new(NodepoolConfidentialNodes)
		**out = **in
	}
	if in.DiskSizeGb != nil {
		in, out := &in.DiskSizeGb, &out.DiskSizeGb
		*out = new(int64)
		**out = **in
	}
	if in.DiskType != nil {
		in, out := &in.DiskType, &out.DiskType
		*out = new(string)
		**out = **in
	}
	if in.EphemeralStorageConfig != nil {
		in, out := &in.EphemeralStorageConfig, &out.EphemeralStorageConfig
		*out = new(NodepoolEphemeralStorageConfig)
		**out = **in
	}
	if in.EphemeralStorageLocalSsdConfig != nil {
		in, out := &in.EphemeralStorageLocalSsdConfig, &out.EphemeralStorageLocalSsdConfig
		*out = new(NodepoolEphemeralStorageLocalSsdConfig)
		**out = **in
	}
	if in.FastSocket != nil {
		in, out := &in.FastSocket, &out.FastSocket
		*out = new(NodepoolFastSocket)
		**out = **in
	}
	if in.GcfsConfig != nil {
		in, out := &in.GcfsConfig, &out.GcfsConfig
		*out = new(NodepoolGcfsConfig)
		**out = **in
	}
	if in.GuestAccelerator != nil {
		in, out := &in.GuestAccelerator, &out.GuestAccelerator
		*out = make([]NodepoolGuestAccelerator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gvnic != nil {
		in, out := &in.Gvnic, &out.Gvnic
		*out = new(NodepoolGvnic)
		**out = **in
	}
	if in.HostMaintenancePolicy != nil {
		in, out := &in.HostMaintenancePolicy, &out.HostMaintenancePolicy
		*out = new(NodepoolHostMaintenancePolicy)
		**out = **in
	}
	if in.ImageType != nil {
		in, out := &in.ImageType, &out.ImageType
		*out = new(string)
		**out = **in
	}
	if in.KubeletConfig != nil {
		in, out := &in.KubeletConfig, &out.KubeletConfig
		*out = new(NodepoolKubeletConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LinuxNodeConfig != nil {
		in, out := &in.LinuxNodeConfig, &out.LinuxNodeConfig
		*out = new(NodepoolLinuxNodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalNvmeSsdBlockConfig != nil {
		in, out := &in.LocalNvmeSsdBlockConfig, &out.LocalNvmeSsdBlockConfig
		*out = new(NodepoolLocalNvmeSsdBlockConfig)
		**out = **in
	}
	if in.LocalSsdCount != nil {
		in, out := &in.LocalSsdCount, &out.LocalSsdCount
		*out = new(int64)
		**out = **in
	}
	if in.LoggingVariant != nil {
		in, out := &in.LoggingVariant, &out.LoggingVariant
		*out = new(string)
		**out = **in
	}
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MinCpuPlatform != nil {
		in, out := &in.MinCpuPlatform, &out.MinCpuPlatform
		*out = new(string)
		**out = **in
	}
	if in.NodeGroupRef != nil {
		in, out := &in.NodeGroupRef, &out.NodeGroupRef
		*out = new(v1alpha1.ResourceRef)
		**out = **in
	}
	if in.OauthScopes != nil {
		in, out := &in.OauthScopes, &out.OauthScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Preemptible != nil {
		in, out := &in.Preemptible, &out.Preemptible
		*out = new(bool)
		**out = **in
	}
	if in.ReservationAffinity != nil {
		in, out := &in.ReservationAffinity, &out.ReservationAffinity
		*out = new(NodepoolReservationAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceLabels != nil {
		in, out := &in.ResourceLabels, &out.ResourceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SandboxConfig != nil {
		in, out := &in.SandboxConfig, &out.SandboxConfig
		*out = new(NodepoolSandboxConfig)
		**out = **in
	}
	if in.ServiceAccountRef != nil {
		in, out := &in.ServiceAccountRef, &out.ServiceAccountRef
		*out = new(v1alpha1.ResourceRef)
		**out = **in
	}
	if in.ShieldedInstanceConfig != nil {
		in, out := &in.ShieldedInstanceConfig, &out.ShieldedInstanceConfig
		*out = new(NodepoolShieldedInstanceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SoleTenantConfig != nil {
		in, out := &in.SoleTenantConfig, &out.SoleTenantConfig
		*out = new(NodepoolSoleTenantConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Spot != nil {
		in, out := &in.Spot, &out.Spot
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Taint != nil {
		in, out := &in.Taint, &out.Taint
		*out = make([]NodepoolTaint, len(*in))
		copy(*out, *in)
	}
	if in.WorkloadMetadataConfig != nil {
		in, out := &in.WorkloadMetadataConfig, &out.WorkloadMetadataConfig
		*out = new(NodepoolWorkloadMetadataConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolNodeConfig.
func (in *NodepoolNodeConfig) DeepCopy() *NodepoolNodeConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolPlacementPolicy) DeepCopyInto(out *NodepoolPlacementPolicy) {
	*out = *in
	if in.PolicyNameRef != nil {
		in, out := &in.PolicyNameRef, &out.PolicyNameRef
		*out = new(v1alpha1.ResourceRef)
		**out = **in
	}
	if in.TpuTopology != nil {
		in, out := &in.TpuTopology, &out.TpuTopology
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolPlacementPolicy.
func (in *NodepoolPlacementPolicy) DeepCopy() *NodepoolPlacementPolicy {
	if in == nil {
		return nil
	}
	out := new(NodepoolPlacementPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolPodCidrOverprovisionConfig) DeepCopyInto(out *NodepoolPodCidrOverprovisionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolPodCidrOverprovisionConfig.
func (in *NodepoolPodCidrOverprovisionConfig) DeepCopy() *NodepoolPodCidrOverprovisionConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolPodCidrOverprovisionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolReservationAffinity) DeepCopyInto(out *NodepoolReservationAffinity) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolReservationAffinity.
func (in *NodepoolReservationAffinity) DeepCopy() *NodepoolReservationAffinity {
	if in == nil {
		return nil
	}
	out := new(NodepoolReservationAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolSandboxConfig) DeepCopyInto(out *NodepoolSandboxConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolSandboxConfig.
func (in *NodepoolSandboxConfig) DeepCopy() *NodepoolSandboxConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolSandboxConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolShieldedInstanceConfig) DeepCopyInto(out *NodepoolShieldedInstanceConfig) {
	*out = *in
	if in.EnableIntegrityMonitoring != nil {
		in, out := &in.EnableIntegrityMonitoring, &out.EnableIntegrityMonitoring
		*out = new(bool)
		**out = **in
	}
	if in.EnableSecureBoot != nil {
		in, out := &in.EnableSecureBoot, &out.EnableSecureBoot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolShieldedInstanceConfig.
func (in *NodepoolShieldedInstanceConfig) DeepCopy() *NodepoolShieldedInstanceConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolShieldedInstanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolSoleTenantConfig) DeepCopyInto(out *NodepoolSoleTenantConfig) {
	*out = *in
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = make([]NodepoolNodeAffinity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolSoleTenantConfig.
func (in *NodepoolSoleTenantConfig) DeepCopy() *NodepoolSoleTenantConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolSoleTenantConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolStandardRolloutPolicy) DeepCopyInto(out *NodepoolStandardRolloutPolicy) {
	*out = *in
	if in.BatchNodeCount != nil {
		in, out := &in.BatchNodeCount, &out.BatchNodeCount
		*out = new(int64)
		**out = **in
	}
	if in.BatchPercentage != nil {
		in, out := &in.BatchPercentage, &out.BatchPercentage
		*out = new(float64)
		**out = **in
	}
	if in.BatchSoakDuration != nil {
		in, out := &in.BatchSoakDuration, &out.BatchSoakDuration
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolStandardRolloutPolicy.
func (in *NodepoolStandardRolloutPolicy) DeepCopy() *NodepoolStandardRolloutPolicy {
	if in == nil {
		return nil
	}
	out := new(NodepoolStandardRolloutPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolTaint) DeepCopyInto(out *NodepoolTaint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolTaint.
func (in *NodepoolTaint) DeepCopy() *NodepoolTaint {
	if in == nil {
		return nil
	}
	out := new(NodepoolTaint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolUpgradeSettings) DeepCopyInto(out *NodepoolUpgradeSettings) {
	*out = *in
	if in.BlueGreenSettings != nil {
		in, out := &in.BlueGreenSettings, &out.BlueGreenSettings
		*out = new(NodepoolBlueGreenSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxSurge != nil {
		in, out := &in.MaxSurge, &out.MaxSurge
		*out = new(int64)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(int64)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolUpgradeSettings.
func (in *NodepoolUpgradeSettings) DeepCopy() *NodepoolUpgradeSettings {
	if in == nil {
		return nil
	}
	out := new(NodepoolUpgradeSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodepoolWorkloadMetadataConfig) DeepCopyInto(out *NodepoolWorkloadMetadataConfig) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.NodeMetadata != nil {
		in, out := &in.NodeMetadata, &out.NodeMetadata
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodepoolWorkloadMetadataConfig.
func (in *NodepoolWorkloadMetadataConfig) DeepCopy() *NodepoolWorkloadMetadataConfig {
	if in == nil {
		return nil
	}
	out := new(NodepoolWorkloadMetadataConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCIDROverprovisionConfig) DeepCopyInto(out *PodCIDROverprovisionConfig) {
	*out = *in
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCIDROverprovisionConfig.
func (in *PodCIDROverprovisionConfig) DeepCopy() *PodCIDROverprovisionConfig {
	if in == nil {
		return nil
	}
	out := new(PodCIDROverprovisionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationAffinity) DeepCopyInto(out *ReservationAffinity) {
	*out = *in
	if in.ConsumeReservationType != nil {
		in, out := &in.ConsumeReservationType, &out.ConsumeReservationType
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationAffinity.
func (in *ReservationAffinity) DeepCopy() *ReservationAffinity {
	if in == nil {
		return nil
	}
	out := new(ReservationAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceManagerTags) DeepCopyInto(out *ResourceManagerTags) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceManagerTags.
func (in *ResourceManagerTags) DeepCopy() *ResourceManagerTags {
	if in == nil {
		return nil
	}
	out := new(ResourceManagerTags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxConfig) DeepCopyInto(out *SandboxConfig) {
	*out = *in
	if in.SandboxType != nil {
		in, out := &in.SandboxType, &out.SandboxType
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxConfig.
func (in *SandboxConfig) DeepCopy() *SandboxConfig {
	if in == nil {
		return nil
	}
	out := new(SandboxConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondaryBootDisk) DeepCopyInto(out *SecondaryBootDisk) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.DiskImage != nil {
		in, out := &in.DiskImage, &out.DiskImage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondaryBootDisk.
func (in *SecondaryBootDisk) DeepCopy() *SecondaryBootDisk {
	if in == nil {
		return nil
	}
	out := new(SecondaryBootDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondaryBootDiskUpdateStrategy) DeepCopyInto(out *SecondaryBootDiskUpdateStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondaryBootDiskUpdateStrategy.
func (in *SecondaryBootDiskUpdateStrategy) DeepCopy() *SecondaryBootDiskUpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(SecondaryBootDiskUpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShieldedInstanceConfig) DeepCopyInto(out *ShieldedInstanceConfig) {
	*out = *in
	if in.EnableSecureBoot != nil {
		in, out := &in.EnableSecureBoot, &out.EnableSecureBoot
		*out = new(bool)
		**out = **in
	}
	if in.EnableIntegrityMonitoring != nil {
		in, out := &in.EnableIntegrityMonitoring, &out.EnableIntegrityMonitoring
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShieldedInstanceConfig.
func (in *ShieldedInstanceConfig) DeepCopy() *ShieldedInstanceConfig {
	if in == nil {
		return nil
	}
	out := new(ShieldedInstanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SoleTenantConfig) DeepCopyInto(out *SoleTenantConfig) {
	*out = *in
	if in.NodeAffinities != nil {
		in, out := &in.NodeAffinities, &out.NodeAffinities
		*out = make([]SoleTenantConfig_NodeAffinity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SoleTenantConfig.
func (in *SoleTenantConfig) DeepCopy() *SoleTenantConfig {
	if in == nil {
		return nil
	}
	out := new(SoleTenantConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SoleTenantConfig_NodeAffinity) DeepCopyInto(out *SoleTenantConfig_NodeAffinity) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SoleTenantConfig_NodeAffinity.
func (in *SoleTenantConfig_NodeAffinity) DeepCopy() *SoleTenantConfig_NodeAffinity {
	if in == nil {
		return nil
	}
	out := new(SoleTenantConfig_NodeAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCondition) DeepCopyInto(out *StatusCondition) {
	*out = *in
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.CanonicalCode != nil {
		in, out := &in.CanonicalCode, &out.CanonicalCode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCondition.
func (in *StatusCondition) DeepCopy() *StatusCondition {
	if in == nil {
		return nil
	}
	out := new(StatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualNIC) DeepCopyInto(out *VirtualNIC) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualNIC.
func (in *VirtualNIC) DeepCopy() *VirtualNIC {
	if in == nil {
		return nil
	}
	out := new(VirtualNIC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WindowsNodeConfig) DeepCopyInto(out *WindowsNodeConfig) {
	*out = *in
	if in.OsVersion != nil {
		in, out := &in.OsVersion, &out.OsVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WindowsNodeConfig.
func (in *WindowsNodeConfig) DeepCopy() *WindowsNodeConfig {
	if in == nil {
		return nil
	}
	out := new(WindowsNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadMetadataConfig) DeepCopyInto(out *WorkloadMetadataConfig) {
	*out = *in
	if in.NodeMetadata != nil {
		in, out := &in.NodeMetadata, &out.NodeMetadata
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadMetadataConfig.
func (in *WorkloadMetadataConfig) DeepCopy() *WorkloadMetadataConfig {
	if in == nil {
		return nil
	}
	out := new(WorkloadMetadataConfig)
	in.DeepCopyInto(out)
	return out
}
